### ISSUE TITLE
Document that --run-dev adds --define process.env.NODE_ENV="development"

### ISSUE THREAD

**Issue by blaise-io** [webpack-contrib/webpack-command#13]
https://github.com/webpack-contrib/webpack-command#cli

Currently it's expected but not documented that `--run-dev` adds `--define process.env.NODE_ENV="development"`. I think it should be documented to save developers some time verifying whether this behaves like expected.

**Comment by shellscape** [comment]
Sad panda 🐼 😢  You removed the issue template, so we have to close your issue as invalid. Please don't ignore Issue or Pull Request templates.
