### ISSUE TITLE
Support JSON stats output

### ISSUE THREAD

**Issue by billyjanitsch** [webpack-contrib/webpack-command#16]
* Operating System: macOS 10.13.4
* Node Version: 10.0.0
* NPM Version: 6.0.0
* webpack Version: 4.8.1
* webpack-command Version: 0.2.0

This issue is for a:

- [ ] **bug**
- [x] **feature** request
- [ ] **modification** request

##### CLI Command

```console
  $ webpack --json
```

##### webpack.config.js

n/a

### Expected Behavior

webpack-cli (and formerly the bundled webpack CLI) has a `--json` arg which causes the stats to be printed out as JSON. This is extremely useful for piping into files which can then be uploaded to web-based [bundle](https://github.com/webpack-contrib/webpack-bundle-analyzer) [analysis](https://github.com/webpack/analyse) [tools](http://chrisbateman.github.io/webpack-visualizer/).

It would be great if webpack-command could support this flag or something equivalent -- perhaps through a reporter. Since webpack-command is already working with the JSON stats, I assume this would be a low-overhead feature to support.

I'm about to take a vacation but I might be able to get a PR out before I leave if this sounds reasonable to you.

### Actual Behavior

There is currently no way to get the build stats as JSON.

### New Feature Use Case

See expected behavior above.

**Comment by billyjanitsch** [comment]
Cool. I will PR a JSON reporter either before or after my vacation.

[These lines](https://github.com/webpack-contrib/webpack-command/blob/338d4bc71b6c69b8cf8dc140aa7476396da10aa2/lib/compiler.js#L96-L102) will be a problem because there is no way to disable them, and it's important that this reporter print _only_ a single valid JSON object. Do you mind if I change the internals to allow the reporter to disable all other output, or is there a better option?

**Comment by shellscape** [comment]
You can actually pull some trickery with that `log` object. In the constructor for your reporter:

```js
this.log = weblog({ name: 'webpack', id: 'webpack-command' });
this.setLogLevel = log.logLevel;
log.logLevel = 'silent';
```

And then in the `render` method for your reporter, restore the level:

```js
this.log.logLevel = this.setLogLevel;
```

Though I'm not sure if that's needed, especially if your reporter is only intended to report JSON and nothing more. Something else to consider: writing the JSON output to `stderr` so you can still allow the logging as per usual, but then could redirect `stderr` to a file or for examination by another process. That'd be the best of both worlds.

**Comment by valscion** [comment]
> Something else to consider: writing the JSON output to stderr so you can still allow the logging as per usual, but then could redirect stderr to a file or for examination by another process. That'd be the best of both worlds.

Could we instead do the opposite? If I'm not mistaken, it's common practice to log informational output to `stderr` if `stdout` will be used for e.g. piping.

Here's one nice blog post summarizing what I've understood `stderr` and `stdout` should be used for: https://www.jstorimer.com/blogs/workingwithcode/7766119-when-to-use-stderr-instead-of-stdout

**Comment by shellscape** [comment]
@valscion welcome to the nuances of writing tooling in the webpack ecosystem: no matter how many considerations you make for how people are going to work with a thing, someone will always have another method they're asking to account for 😄 

There hasn't been a huge demand for this yet, so I really have no preference for how this functions. No one has stepped up to provide this in a PR yet.

**Comment by shellscape** [comment]
> I hope my comment wasn't coming through as assertative. Didn't mean to bring bad feelings. (I feel the need to apologise as your reply comes off a bit snarky, and I worry it's my fault)

Tangent: I believe people anymore are way too worried about the mere possibility of offending someone. My reply contained no snark, it was straight truth. And it even had a smiley face. If your reply offended anyone, they can go jump in a lake, because it was perfectly fine and properly illustrated the nuances I mentioned.
