### ISSUE TITLE
Allow a way to disable update-notifier

### ISSUE THREAD

**Issue by alexeagle** [webpack-contrib/webpack-command#17]
* Operating System: Linux
* Node Version: 8.9.1
* NPM Version: n/a
* webpack Version: 4.8.1
* webpack-command Version: 0.2.0

This issue is for a:

- [ ] **bug**
- [x] **feature** request
- [ ] **modification** request

##### CLI Command

I run build steps under a containerized filesystem sandbox (this is for the Bazel build which does this to enable remote build execution.)

I suspect that's why any execution of `webpack-command` prints
```
┌──────────────────────────────────────────────────────────────────────────────┐
│                     webpack-command update check failed                      │
│                     Try running with sudo or get access                      │
│                     to the local update config store via                     │
│ sudo chown -R $USER:$(id -gn $USER) /usr/local/google/home/alexeagle/.config │
└──────────────────────────────────────────────────────────────────────────────┘
```

### Expected Behavior

Either update-notifier should be quiet when it's running in a context where it can't work (not sure if feasible)
or webpack-command would let me disable this output, either directly or via `--log-level` or `--reporter`

### Actual Behavior
Always get this ugly error for any build step that runs webpack-command

### How Do We Reproduce?

- Install Bazel
- Clone https://github.com/alexeagle/rules_nodejs/tree/webpack
- `bazel build internal/webpack/test`

**Comment by shellscape** [comment]
Thanks for the issue 🍺 

This is one of those sticky wickets that falls into the _opinionated_ category. If you can convince `npm` to allow disabling their update notice, I'll follow suit. Until then, I'm afraid stays. FWIW, we're using the same package for this as `npm`. I'm gonna tag this _won't fix_ and _waiting on upstream_ in the event they've introduced a configuration option to disable that, or you manage to convince them to that effect :smile:

**Comment by alexeagle** [comment]
But it's not npm doing this behavior, there's an explicit call here
https://github.com/webpack-contrib/webpack-command/blob/master/lib/index.js#L13
which I imagine being guarded

**Comment by shellscape** [comment]
You may have missed my point there. I'm not saying that `npm` is performing that check. I'm saying that `webpack-command` (as well as `webpack-serve`) uses the _same method and module_ that `npm` does to perform its update check. Keeping users apprised of new versions is a good thing, and it outweighs the inconvenience of an extraneous log message in environments where it isn't necessarily needed. The same can be seen when running `npm` in a CI environment. Providing an option to disable the feature is not something that `npm` does, and it's not something that `webpack-command` does at this time.

**Comment by ankurk91** [comment]
One can disable "check for updates" by adding an environment variable
```
NO_UPDATE_NOTIFIER
```
or you can pass `--no-update-notifier` in cli

https://github.com/yeoman/update-notifier#user-settings

**Comment by shellscape** [comment]
Closing citing comment by @ankurk91
