### ISSUE TITLE
Arguments not passed to webpack config

### ISSUE THREAD

**Issue by Demivan** [webpack-contrib/webpack-command#23]
* Operating System: Windows 10
* Node Version: 9.11.1
* NPM Version: 5.6.0
* webpack Version: 4.10.0
* webpack-command Version: 0.2.0

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [x] **modification** request

##### CLI Command

```console
  $ webpack --mode=production
```

##### webpack.config.js

```js
module.exports = function (argv) {
  const production = argv.mode === 'production'
  ...
}
```

### Expected Behavior

Function should be called with arguments passed to CLI, just like with webpack-cli. For example:
```js
 { mode: 'production' }
```

### Actual Behavior

Function is called without arguments.

### How Do We Reproduce?

Export function from webpack config.

### Investigation

I can see that webpack-command uses config-loader for loading webpack config.
config-loader has this functionality described in https://github.com/webpack-contrib/config-loader#gotchas, but as far as I can see, default exported function from config-loader does not actually call config with arguments. webpack-command does not pass them to config-loader either. So I'm sure where to report this bug.

**Comment by shellscape** [comment]
Thanks for the issue :beer: The correct place for this issue would be `config-loader`. `webpack-command` doesn't have any control over that functionality.

**Comment by Demivan** [comment]
Ok. But function that `webpack-command` uses does not actually pass them to `resolve` method: https://github.com/webpack-contrib/config-loader/blob/1c85b99de26903db1643e799aed1182a0bc38fd2/lib/index.js#L15. So `webpack-command` will need changes too.
