### ISSUE TITLE
'mode' is not found in multi compiler configuration

### ISSUE THREAD

**Issue by mjdease** [webpack-contrib/webpack-command#27]
* Operating System: macOS 10.13.5
* Node Version: 9.5.0
* NPM Version: 6.1.0
* webpack Version: 4.11.0
* webpack-command Version: 0.2.0

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### CLI Command

```console
  $ webpack
```

##### webpack.config.js

```js
module.exports = [
  {
    mode: 'production',
    entry: './index.js',
    output: {
      filename: 'lib-prod.js'
    },
  },
  {
    mode: 'development',
    entry: './index.js',
    output: {
      filename: 'lib-dev.js'
    },
  },
];
```

```js
// index.js
console.log('start');

if (process.env.NODE_ENV !== 'production') {
  console.log('dev mode');
}
```

### Expected Behavior

I expect this configuration to run two builds, one in dev mode and one in prod mode.

See this example for a more realistic use of a multi compiler setup https://github.com/webpack/webpack/tree/master/examples/multi-compiler

### Actual Behavior

A warning for each entry is logged:
```
  0:0  warning  The 'mode' option has not been set, webpack will fallback to
                'production' for this value. Set 'mode' option to 'development' or
                'production' to enable defaults for each environment.
```

And each build output is indeed built in production mode.

The build works as expected using `webpack-cli`

### How Do We Reproduce?

Run the provided cli command with the webpack config and source file.

**Comment by shellscape** [comment]
Thanks for the issue :beer: But this is not likely a `webpack-command` bug. It's entirely possible that `webpack-cli` does something custom around this that is undocumented. However, `webpack-command` passes your config onto webpack's API directly. The only situation in which it's modified is when CLI flags are used. I suggest using the webpack API directly (which is quite simple for a config this simple) to debug your config first.

**Comment by mjdease** [comment]
@shellscape I wrote a node script that uses the `webpack` api directly with my above config and it builds as expected:

```js
// build.js
const webpack = require("webpack");

const compiler = webpack([
  {
    mode: 'production',
    entry: './index.js',
    output: {
      filename: 'lib-prod.js'
    },
  },
  {
    mode: 'development',
    entry: './index.js',
    output: {
      filename: 'lib-dev.js'
    },
  },
]);

compiler.run((err, stats) => {
  console.log('done');

  if (err) {
    console.error(err.stack || err);
    if (err.details) {
      console.error(err.details);
    }
    return;
  }

  const info = stats.toJson();

  if (stats.hasErrors()) {
    console.error(info.errors);
  }

  if (stats.hasWarnings()) {
    console.warn(info.warnings);
  }
});
```

**Comment by shellscape** [comment]
Here's the offending line https://github.com/webpack-contrib/webpack-command/blob/4c7108ca21db0b2758d9704e575fae71d697eb7b/lib/flags/config.js#L11 That looks innocuous, but then in https://github.com/webpack-contrib/webpack-command/blob/4c7108ca21db0b2758d9704e575fae71d697eb7b/lib/config.js#L14 an aggressive merge is used, which sets the `mode` to `undefined`, resulting in that error. (You'll notice on line 24 following, a non-aggressive merge is used. Which is also a bug)

**Comment by shellscape** [comment]
Fix is published

**Comment by jscinoz** [comment]
That was very fast! Thank you!
