### ISSUE TITLE
Environment variables don't seem to work

### ISSUE THREAD

**Issue by danawoodman** [webpack-contrib/webpack-command#28]
* Operating System: OSX
* Node Version: 10.3.0
* NPM Version: 6.0.1
* webpack Version: 4.10.2
* webpack-command Version: 0.2.0

This issue is for a:

- [ ] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### CLI Command

```console
  $ FOO='bar' webpack
```

##### webpack.config.js

None...

##### Other code

`src/index.js`:

```js
console.log(process.env.FOO) // undefined
```

Also doesn't work:

```js
console.log(process.env) // {}
```

### Expected Behavior

This code, according to docs, should log `'bar'` to the console.

### Actual Behavior

It actually logs `undefined`, which is unexpected.

### How Do We Reproduce?

Doing above

**Comment by shellscape** [comment]
Thanks for the issue :beer:

Definitely not a bug. I'm not sure your expectation here is correct. It seems that you're expecting the Node `process.env` to be available in the built bundle, which is a separate environment. I'm not sure if this expectation is the result of a wonky hack that exists in `webpack-cli`, but there are other, better ways to get access to variables in a bundle. Namely the `DefinePlugin`.

**Comment by danawoodman** [comment]
Ahhhhhhh, gotcha. I'm used to using `DefinePlugin` but for some reason assumed `webpack-command` did some magic, but that makes sense. Thanks!

**Comment by shellscape** [comment]
No worries!
