### ISSUE TITLE
exit code is always 0

### ISSUE THREAD

**Issue by MrMamen** [webpack-contrib/webpack-command#31]
* Operating System: Ubuntu 18.04
* Node Version: v8.10.0
* NPM Version: 6.0.0
* webpack Version: 4.9.1
* webpack-command Version: 0.2.0

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

### Expected Behavior
If any errors occurs I expect some exit code > 0.

### Actual Behavior
exit code is 0

### How Do We Reproduce?

put some invalid code before running webpack

**Comment by shellscape** [comment]
@MrMamen Please _do not_ remove portions of an issue template, or your issue will be marked as invalid and closed in the future. Please also make an effort in the future to provide a complete issue:

> put some invalid code before running webpack

That helps no one understand your issue, as it lacks any context for which you might be seeing the issue. You also didn't provide any code; a webpack config and/or code which is generating an error for which you expect to see a different exit code.

**Comment by MrMamen** [comment]
This is the simplest example I can find. The only thing I did was creating an empty directory before running webpack-command with no config files or parameters:

> $ ../../node_modules/.bin/webpack
> ℹ ｢webpack｣: Starting Build
> ℹ ｢webpack｣: Build Finished
> 
> webpack v4.9.1
> 
> 44224b95b411030deb1a
>   size  name  module  status
> 
>   Δt 44ms 
> 
> 
> Entry module not found: Error: Can't resolve './src' in '/home/mrmamen/development/test'
>   0:0  error  webpack-stylish: <please report unknown message format>
> 
> configuration
>   0:0  warning  The 'mode' option has not been set, webpack will fallback to
>                 'production' for this value. Set 'mode' option to 'development' or
>                 'production' to enable defaults for each environment.
> 
> ✖ 2 problems (1 error, 1 warning)
> 

The exit code is 0. This is revealed by entering echo $? (This is version 0.3, released after this issue was opened)

**Comment by shellscape** [comment]
@MrMamen thanks. we released a new version with a fix for this.

**Comment by MrMamen** [comment]
@shellscape OK I'll have another look when v0.3.1 or v0.4.0 is public

**Comment by MrMamen** [comment]
The error still occurs on v0.3.1
