### ISSUE TITLE
Not respecting `context` in webpack.config.js

### ISSUE THREAD

**Issue by alexilyaev** [webpack-contrib/webpack-command#36]
* Operating System: macOS 10.13.4
* Node Version: v10.4.1
* Yarn Version: 1.6.0
* webpack Version: 4.12.0
* webpack-command Version: 0.2.1

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

### Code
https://github.com/alexilyaev/react-es6-starter/tree/webpack-command-context-bug

##### CLI Command

```console
  $ npm run build
```

##### webpack.config.js

https://github.com/alexilyaev/react-es6-starter/blob/webpack-command-context-bug/webpack.config.js

### Expected Behavior

`npm run build` should succeed.

### Actual Behavior

Fails with:

```
> cross-env NODE_ENV=production webpack

clean-webpack-plugin: /Users/alex/www/Node/Personal/react-es6-starter/dist has been removed.
ℹ ｢webpack｣: Starting Build
ℹ ｢webpack｣: Build Finished

webpack v4.12.0

475330bd3c812c147ff4
  size  name  module  status

  Δt 581ms


Entry module not found: Error: Can't resolve './app.js' in '/Users/alex/www/Node/Personal/react-es6-starter'
  0:0  error  webpack-stylish: <please report unknown message format>

Error: Child compilation failed:
  253:16  error  Entry module not found: Error: Can't resolve
                 '/Users/alex/www/Node/Personal/react-es6-starter/app.html' in
                 '/Users/alex/www/Node/Personal/rea  ct-es6-starter':   Error: Can't
                 resolve '/Users/alex/www/Node/Personal/react-es6-starter/app.html' in
                 '/Users/alex/www/Node/Personal/react-es6-starter'      - compiler.js:79
                 childCompiler.runAsChild
                 [react-es6-starter]/[html-webpack-plugin]/lib/compiler.js:      -
                 Compiler.js:243 compile
                 [react-es6-starter]/[webpack]/lib/Compiler.js:243:11      -
                 Compiler.js:500 hooks.afterCompile.callAsync.err
                 [react-es6-starter]/[webpack]/lib/Compiler.js:500:14         -
                 Hook.js:35 AsyncSeriesHook.lazyCompileHook [as _callAsync]
                 [react-es6-starter]/[tapable]/lib/Hook.js:35:21      - Compiler.js:497
                 compilation.seal.err
                 [react-es6-starter]/[webpack]/lib/Compiler.js:497:30         -
                 Hook.js:35 AsyncSeriesHook.lazyCompileHook [as _callAsync]
                 [react-es6-starter]/[tapable]/lib/Hook.js:35:21      -
                 Compilation.js:986 hooks.optimizeAssets.callAsync.err
                 [react-es6-starter]/[webpack]/lib/Compilation.js:986:35         -
                 Hook.js:35 AsyncSeriesHook.lazyCompileHook [as _callAsync]
                 [react-es6-starter]/[tapable]/lib/Hook.js:35:21      -
                 Compilation.js:977 hooks.optimizeChunkAssets.callAsync.err
                 [react-es6-starter]/[webpack]/lib/Compilation.js:977:32         -
                 index.js:334
                 [react-es6-starter]/[uglifyjs-webpack-plugin]/dist/index.js:334:11
                 - index.js:63 _class.runTasks
                 [react-es6-starter]/[uglifyjs-webpack-plugin]/dist/uglify/index.js:63:9
                 - index.js:253 UglifyJsPlugin.optimizeFn

✖ 2 problems (2 errors, 0 warnings)
```

### How Do We Reproduce?

- Clone
- `yarn`
- `npm run build`

## Other Notes

- `context` is not respected
- Works ok with webpack-cli

**Comment by shellscape** [comment]
_Note: Please don't modify the issue templates. `npm` is the only officially supported package manager for this repository and project, and that's the reason it's listed as required information._

Please do poke around before opening an issue. A quick search of this repository will show that this module does not modify the `context` of a config unless one is specified in a command line flag, and without a flag specifying the context, your config is passed along to `webpack` proper via the API.

The error likely resides in your config. If you can point to an inconsistency between webpack-cli and webpack-command that is responsible for this, that would be helpful, though we're not aware of any at the moment and our tests presently run with contexts successfully.

**Comment by alexilyaev** [comment]
@shellscape Thanks for the quick reply.
npm - v6.1.0

Let me share my experience...
I'm a consultant, devs usually ask me about the latest release of different packages.  
With Webpack, I knew it's going to take some time for things to settle after the v4 release.  
Finally I've decided to migrate v3 to v4. I've read the whole changelog (from v4 and above) and re-visited the docs.

The first thing in v4 is that it asked me to install a cli tool. So I read about `webpack-command` and then read the blog post that `webpack-cli` is going to be deprecated, so I installed it.  
Took me few hours to update my config, checking every option.  
`webpack-dev-server` failed first, it has an implicit dependency on `webpack-cli` (there's an open issue).  
Then running the build failed, with the error I mentioned.

So I installed `webpack-cli` and removed `webpack-command` and everything works.  
Which leads me to the point, it's the same config and it works with webpack-cli, so I was surprised there's an issue with `context` when using `webpack-command`.

Appreciate your help.

**Comment by shellscape** [comment]
Thanks for the context about how you arrived here. But that still doesn't give us any kind of indication that this is a bug, citing the tests that all run fine with context, and that this hasn't been reported before. If `context` were truly being ignored, we'd have a metric poopton of issues being opened about it. Given that, you should triage this issue on your end to provide a more granular cause of the issue case on your end, from which we can move forward.

**Comment by alexilyaev** [comment]
@shellscape So... in the description I've shared this repo with a specific branch where the problem occurs, it looks like a basic config with `context`.

When I run it, it fails.
Can you elaborate on how exactly I can dig deeper?

Or maybe, could you run it for a sec, maybe you'll see something straight away.

**Comment by jgerigmeyer** [comment]
I've been hitting this bug as well with v0.2.1 (it works fine on v0.2.0).

* Operating System: macOS 10.13.5
* Node Version: 10.3.0
* NPM Version: 6.1.0
* webpack Version: 4.12.0
* webpack-command Version: 0.2.1



This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

### Code

##### CLI Command

```console
  $ webpack
```

##### webpack.config.js

```js
const path = require('path');
const webpack = require('webpack');

module.exports = {
  mode: 'development',
  // context for entry points
  context: path.join(__dirname, 'static', 'js'),
  // define all the entry point bundles
  entry: {
    app: './init.js',
  },
  output: {
    path: path.join(__dirname, 'content', 'static', 'assets'),
    publicPath: '/static/assets/',
    filename: '[name].bundle.js',
  },
  resolve: {
    // where to look for "required" modules
    modules: ['static/js', 'templates', 'sass', 'static', 'node_modules'],
    alias: { jquery: 'jquery/dist/jquery.slim.js' },
  },
  optimization: {
    runtimeChunk: 'single',
    splitChunks: {
      name: false,
    },
  },
  plugins: [
    // make jquery accessible in all modules that use it
    new webpack.ProvidePlugin({
      $: 'jquery',
      jQuery: 'jquery',
      'window.jQuery': 'jquery',
      'root.jQuery': 'jquery',
    }),
  ],
  module: {
    rules: [
      {
        test: /(static\/js\/.*\.js$|test\/.*\.js$)/,
        exclude: /(node_modules|vendor)/,
        use: [
          {
            loader: 'babel-loader',
            options: { cacheDirectory: true },
          },
        ],
      },
    ],
  },
};
```

### Expected Behavior

`webpack-command` v0.2.0:

```
ℹ ｢webpack｣: Starting Build
ℹ ｢webpack｣: Build Finished

webpack v4.12.0

d8770d5d615893b45708
  size     name     module             status
  5.38 kB  base.js  ./app/base.js      built
  152 B    init.js  ./init.js          built

  size     name     asset              status
  301 kB   app      app.bundle.js      emitted
  6.2 kB   runtime  runtime.bundle.js  emitted

  Δt 1425ms (35 modules hidden)
```

### Actual Behavior

`webpack-command` v0.2.1:

```
ℹ ｢webpack｣: Starting Build
ℹ ｢webpack｣: Build Finished

webpack v4.12.0

a293ba96e559b9f271af
  size  name  module  status

  Δt 106ms


Entry module not found: Error: Can't resolve './init.js' in '/Users/jonny/Sites/oddsite'
  0:0  error  webpack-stylish: <please report unknown message format>

✖ 1 problem (1 error, 0 warnings)
```

### How Do We Reproduce?

From repo: https://github.com/oddbird/oddsite/tree/webpack-command-bug
Run `npm install` (on `webpack-command-bug` branch), and then `webpack` (or `./node_modules/.bin/webpack`).

**Comment by karzac** [comment]
I have the same issue. It works fine with 0.2.0 version. But fails on 0.2.1

**Comment by shellscape** [comment]
@jgerigmeyer rather than trying to be clever, you could invest some time into triaging the issue and finding a cause 😉 

@karzac please don't post "me too" comments. It actually doesn't contribute to the issue, only creates extra noise and notifications for the issue. Instead, please use the [reaction button ](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to lend support to the original post, or a particular existing reply.

**Comment by LynnKirby** [comment]
I have to re-setup my development environment before I can make a proper PR, but I found the problem [here](https://github.com/webpack-contrib/webpack-command/blob/75ff73c1389f1c4575318116185d8bbe8b7aa515/lib/flags/general.js#L41). The CLI flag parser uses `process.cwd()` if the `--context` flag isn't set, overriding the config file setting.
