### ISSUE TITLE
webpack output contains duplicated dependencies after upgrading to 0.3.0

### ISSUE THREAD

**Issue by vitalyster** [webpack-contrib/webpack-command#41]
* Operating System: Windows 10
* Node Version: 8.11.3
* NPM Version: 5.6.0
* webpack Version: 4.12.2
* webpack-command Version: 0.3.0

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### CLI Command

```console
  $ webpack -p
```

##### webpack.config.js

https://gist.github.com/vitalyster/9524813d2905f827246623084296e25e - here is the demo app including webpack.config.js

### Expected Behavior

My app uses react, output have app.js and vendor.js chunks, vendor.js should contain react.production.min.js and react-dom.production.min.js (copyright comments containing these names should be there too). webpack-cli and webpack-command@0.2.1 are working as expected

### Actual Behavior

After upgrading from 0.2.1 to 0.3.0 output contains react(-dom).production AND react-(dom).development

### How Do We Reproduce?

1. `npm run dist` in my gist directory and check dist/ directory
2. `npm install --save-dev webpack-command@0.2.1 && npm run dist` will make correct output

**Comment by shellscape** [comment]
@vitalyster thanks for the issue :beer:

Are your `yarn` scripts compatible with `npm`?
When you say "output" are you referencing the console output or the filesystem output?

**Comment by vitalyster** [comment]
@shellscape actually it's just `webpack -p` filesystem output

**Comment by shellscape** [comment]
OK I'll investigate. There might be a regression in the options between the two versions. Can you also try the `--run-prod` flag instead of the `-p` flag?

**Comment by vitalyster** [comment]
@shellscape the same as for `-p`: vendor.js chunk contains both development and production react

**Comment by shellscape** [comment]
OK thanks. I'll investigate.

**Comment by vitalyster** [comment]
It looks like NODE_ENV was defined `"production"` before and `production` after
