### ISSUE TITLE
Error stacktraces aren't showing up

### ISSUE THREAD

**Issue by dietergeerts** [webpack-contrib/webpack-command#43]
* Operating System: Windows 10
* Node Version: 8
* NPM Version: 6
* webpack Version: 4
* webpack-command Version: 0.4.0

### CLI Command

```console
  $ webpack --mode development --watch
```

### Expected Behavior

If an error occurs, the full stack trace should be shown, to be able to solve the issue.
webpack-cli outputs the following:
```

WARNING in ./src/design-tokens/colors.docs.md
Module build failed (from D:/Projects/fabricator-builder/node_modules/extract-loader/lib/extractLoader.js):
ModuleBuildError: Module build failed (from D:/Projects/fabricator-builder/node_modules/vue-loader/lib/index.js):
Error: Cannot find module 'vue-template-compiler'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
....
```

### Actual Behavior

I got this on console, and I can't find any file that output more:
```
  0:0  error  Module build failed (from
              D:/Projects/fabricator-builder/node_modules/vue-loader/lib/index.js):
```

### How Do We Reproduce?

Make sure one of the loaders gives an error.

**Comment by shellscape** [comment]
Which part are you expecting to see that's helpful?

```
Error: Cannot find module 'vue-template-compiler'
```

or

```
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
```

The latter isn't remotely helpful to average users, as that's an internal webpack stacktrace.

**Comment by ankurk91** [comment]
This is the output from webpack-command v0.4.1

**1. When module not found in js**
```
./app/src/js/index.js
  3:0  error  Module not found: Error: Can't resolve 'module-that-was-not-installed'
              in
              '/home/travis/build/ankurk91/webpack-command-exit-code-issue/app/src/js'
```
**2. When sass-loader could not resolve asset**
```
./app/src/sass/index.scss (./node_modules/css-loader??ref--6-1!./node_modules/sass-loader/lib/loader.js??ref--6-2!./app/src/sass/index.scss)
  0:0  error  Module not found: Error: Can't resolve
              './file-that-does-not-exists.png' in
              '/home/travis/build/ankurk91/webpack-command-exit-code-issue/app/src/sass'
```
**3. When there is a syntax error in .scss file**
```
./app/src/sass/index.scss (./node_modules/css-loader??ref--6-1!./node_modules/sass-loader/lib/loader.js??ref--6-2!./app/src/sass/index.scss)
  0:0  error  Module build failed (from ./node_modules/sass-loader/lib/loader.js):
```
The 3rd one could be improved. It should indicate the line number where the syntax error found.

**Comment by dietergeerts** [comment]
@ankurk91 , It's not good for errors in the vue-loader.
@shellscape, the first one would be good, because seeing that error, you know it's from vue-loader, and that's a dependency that's not stated when you install it.

**Comment by ankurk91** [comment]
I have not tried it with Vue loader yet.
I will try with Vue loader and paste error here.
I will also try 
https://github.com/geowarin/friendly-errors-webpack-plugin

If this plugin make a difference.

**Comment by shellscape** [comment]
@ankurk91 the goal for the `StylishReporter` in webpack-command is to make plugins like `friendly-errors-webpack-plugin` unnecessary, so we definitely want to improve how the errors and warnings are rendered. If you have a repo that can reproduce those errors, please share and I'll update the parser for it.

**Comment by ankurk91** [comment]
Here is the repo-
https://github.com/ankurk91/webpack-command-error-reporting-issue

You can see different errors on [TravisCI](https://travis-ci.org/ankurk91/webpack-command-error-reporting-issue/builds/401227676)

I have tried to cover very usual errors in repo.
I found that `vue-loader` is not showing html syntax error in `production` mode.

**Comment by shellscape** [comment]
Thanks for that. I'll try to get to this over the next few days. If you'd like to contribute to the parser for any of these cases, please do open a PR.

**Comment by dietergeerts** [comment]
Thx for looking into this. The `vue-loader` is definitely a strange one, I encountered many other things that it doesn't do like expected and are default behavior for loaders, which leads to unconventional uses if you want to combine it with other loaders/configs.

**Comment by mgcrea** [comment]
Just chiming in as I'm encountering this as well while working on a backend NodeJS setup with webpack (using `babel-loader@8.0.0-beta`):

Babel build errors are not helpful at all!

```
./packages/core-api/src/utils/logger.js
  0:0  error  Module build failed (from ./node_modules/babel-loader/lib/index.js):
```

While the same error directly with babel gives me:

```
$ npx babel packages/core-api/src/utils/logger.js 
{ SyntaxError: /Users/olivier/Projects/mgcrea/starter-kits/nodejs-starter/packages/core-api/src/utils/logger.js: Support for the experimental syntax 'objectRestSpread' isn't currently enabled (69:38):

  67 |     new transports.Console({
  68 |       format: {
> 69 |         transform: ({message, level, ...other}, ...args) => {
     |                                      ^
  70 |           console.dir({message, level, other, args});
  71 |           // {level, message}
  72 |           return {message, level};

Add @babel/plugin-proposal-object-rest-spread (https://git.io/vb4Ss) to the 'plugins' section of your Babel config to enable transformation.
    at Parser.raise (/Users/olivier/Projects/mgcrea/starter-kits/nodejs-starter/node_modules/@babel/parser/lib/index.js:3898:15)
    at Parser.expectPlugin (/Users/olivier/Projects/mgcrea/starter-kits/nodejs-starter/node_modules/@babel/parser/lib/index.js:5232:18)
    at Parser.parseObj (/Users/olivier/Projects/mgcrea/starter-kits/nodejs-starter/node_modules/@babel/parser/lib/index.js:6637:14)
    at Parser.parseExprAtom (/Users/olivier/Projects/mgcrea/starter-kits/nodejs-starter/node_modules/@babel/parser/lib/index.js:6269:21)
    at Parser.parseExprSubscripts (/Users/olivier/Projects/mgcrea/starter-kits/nodejs-starter/node_modules/@babel/parser/lib/index.js:5903:21)
    at Parser.parseMaybeUnary (/Users/olivier/Projects/mgcrea/starter-kits/nodejs-starter/node_modules/@babel/parser/lib/index.js:5882:21)
    at Parser.parseExprOps (/Users/olivier/Projects/mgcrea/starter-kits/nodejs-starter/node_modules/@babel/parser/lib/index.js:5791:21)
    at Parser.parseMaybeConditional (/Users/olivier/Projects/mgcrea/starter-kits/nodejs-starter/node_modules/@babel/parser/lib/index.js:5763:21)
    at Parser.parseMaybeAssign (/Users/olivier/Projects/mgcrea/starter-kits/nodejs-starter/node_modules/@babel/parser/lib/index.js:5710:21)
    at Parser.parseParenAndDistinguishExpression (/Users/olivier/Projects/mgcrea/starter-kits/nodejs-starter/node_modules/@babel/parser/lib/index.js:6449:28)
  pos: 1158,
  loc: Position { line: 69, column: 37 },
  missingPlugin: [ 'objectRestSpread' ],
  code: 'BABEL_PARSE_ERROR' }
```

**Comment by shellscape** [comment]
@mgcrea use the `--reporter basic` flag and you'll get build output as webpack spits it out. it's ugly, but that data you're looking for will be in there. If you'd like to contribute to improving the `stylish` reporter, please open a new issue with a reproducible test case.

**Comment by ZebraNorth** [comment]
Hi,
If it helps save any time, I've tracked this down to line 172 in `webpack-command/lib/reporters/parse.js`.  It does `let [, message] = lines;`, which throws away everything but the first line of the error message.

As a quick hack I changed it to `let message = lines.join("\n");`, although this gets mangled by later processing stages so it's not a fix.

**Comment by shellscape** [comment]
The more likely problem is that babel-loader is adding a string to the compilation's errors, rather than an Error object. It's a bad habit that many loaders and plugins, in and out of webpack, do frequently.

**Comment by dietergeerts** [comment]
@shellscape, even though it's a bad habit, it could be taken into account and make it work, no?

**Comment by youcandanch** [comment]
For what it's worth, this causes issues with the eslint-loader as well. Per @shellscape, using the basic reporting works fine.

Basic:
<img width="709" alt="screen shot 2018-08-18 at 10 09 41 am" src="https://user-images.githubusercontent.com/448732/44300067-e42e4380-a2ce-11e8-81af-69fea8f89029.png">

Default:
<img width="773" alt="screen shot 2018-08-18 at 10 04 05 am" src="https://user-images.githubusercontent.com/448732/44300068-eabcbb00-a2ce-11e8-9022-073a142e5eb6.png">

@shellscape is the fix here actually upstream at each loader that's using strings instead of Error objects, then?

**Comment by youcandanch** [comment]
Also, I can't _quite_ confirm this, but it seems like with the default reporter, a SIGINT actually won't kill the process off if it's mid-build.

**Comment by evilebottnawi** [comment]
DEPRECATED. `webpack-command` is also deprecated. Please use `webpack-cli`. If any features were not implemented in `webpack-cli` feel free to create issue. 

Why deprecated `webpack-command` ?
- `webpack-cli` is very stable and have more features.
- Two CLIs are misleading for developers.
- Hard to maintain two package with same purpose.
- The author stopped developing the package.
- Most of the features are already implemented in `webpack-cli`.

Thanks for using `webpack`! We apologize for the inconvenience. In the future, we will avoid such situations.
