### ISSUE TITLE
Webpack-dev-server support?

### ISSUE THREAD

**Issue by geoshar** [webpack-contrib/webpack-command#45]
hey, nice CLI! And it would be nicer, if it would work also on webpack-dev-server.. Thanks.

**Comment by shellscape** [comment]
Thanks for the kind words? I have no idea what the reference to `webpack-dev-server` means. They're two completely different modules.

**Comment by dk00** [comment]
`webpack-dev-server` is [obsolete](//github.com/webpack/webpack-dev-server/#project-in-maintenance), use [`webpack-serve`](//github.com/webpack-contrib/webpack-serve) instead.

**Comment by marcofugaro** [comment]
@shellscape I think what the guy originally meant is: can also the development mode console output be made human readable? Like this package is doing for the build command.

Example oh what I'm talking about (I think it's from `webpack-dev-middleware`):
![image](https://user-images.githubusercontent.com/7217420/43992274-3bfa4a48-9d7d-11e8-9b5c-72de10e1b4cf.png)
