### ISSUE TITLE
Resolve extended configs via eslint-import-resolver-webpack (or make similar plugin)

### ISSUE THREAD

**Issue by tsnieman** [webpack-contrib/webpack-command#47]
* Operating System: Ubuntu 18.04 n/a
* Node Version: 8 n/a
* NPM Version: 6 n/a
* webpack Version: 4 n/a
* webpack-command Version: 0.4.1

### Expected Behavior / Situation

`eslint-import-resolver-webpack` should understand `webpack-command`'s `extends` config.

### Actual Behavior / Situation

`eslint-import-resolver-webpack` does not understand `webpack-command`'s `extends` config. This results in messages like this:

```
  6:21  error  Unable to resolve path to module 'components/AppRoot'  import/no-unresolved
```

### Modification Proposal

Either:

:one: Make `eslint-import-resolver-webpack` compatible with this plugin's features (namely: `extends`).

:two: Make a similar plugin which is compatible with this plugin's features (namely: `extends`).

-----

*NOTE* Not sure if this is better in `eslint-import-resolver-webpack`'s issues or here, so I'm making one here since this project added the `extends` functionality.

**Comment by shellscape** [comment]
Sounds like a problem with that plugin, and something that should be addressed on their end.

**Comment by tsnieman** [comment]
Fair enough, thanks for the quick response! Figured I'd raise the issue just in case. Closing :x:
