### ISSUE TITLE
Support dynamic entry

### ISSUE THREAD

**Issue by crlfe** [webpack-contrib/webpack-command#48]
* Operating System: Linux
* Node Version: 8.9.1
* NPM Version: 6.1.0
* webpack Version: 4.16.3
* webpack-command Version: 0.4.1

[Dynamic entry](https://webpack.js.org/configuration/entry-context/#dynamic-entry) does not work due to a glitch sanitizing the configuration. This seems to be used most often to have webpack pick up globbed entry points ([example package](https://www.npmjs.com/package/webpack-watched-glob-entries-plugin); getEntries returns a function).

### CLI Command

```console
  $ wp
```

### Code

```js
// webpack.config.js
const { resolve } = require('path');

exports.default = {
    entry: () => resolve(__dirname, 'src/another-missing-file.js'),
}
```

### Expected Behavior

Can't resolve '.../src/another-missing-file.js'

Works as expected with webpack-cli.

### Actual Behavior

Error: Can't resolve './src'

### How Do We Reproduce?

Function has no enumerable properties, so will be discarded by [compiler.js#L83](https://github.com/webpack-contrib/webpack-command/blob/01048bbbebc06f998d6101a087e7f69f15561df7/lib/compiler.js#L83)

Believe adding a `typeof target === 'object'` check is the safe fix. I have a local fix with test if you'd like me to throw up a fork and PR.

**Comment by shellscape** [comment]
> Believe adding a typeof target === 'object' check is the safe fix. I have a local fix with test if you'd like me to throw up a fork and PR.

I disagree. The proper fix would to not enter that loop if the type of the entry value is a function or thenable.

**Comment by crlfe** [comment]
Are we looking at the [same line](https://github.com/webpack-contrib/webpack-command/blob/01048bbbebc06f998d6101a087e7f69f15561df7/lib/compiler.js#L82)? Skipping the loop (and therefore the output cleanup) because of a dynamic entry seems wrong.

The dynamic entry function may return a PromiseLike. Neither the dynamic entry docs nor the [webpack code](https://github.com/webpack/webpack/blob/master/lib/EntryOptionPlugin.js#L32) handle the entry value being PromiseLike.

**Comment by evilebottnawi** [comment]
DEPRECATED. Please use `webpack-cli`. If any features were not implemented in `webpack-cli` feel free to create issue. 

Why deprecated `webpack-command` ?
- `webpack-cli` is very stable and have more features.
- Two CLIs are misleading for developers.
- Hard to maintain two package with same purpose.
- The author stopped developing the package.
- Most of the features are already implemented in `webpack-cli`.

Thanks for using `webpack`! We apologize for the inconvenience. In the future, we will avoid such situations.
