### ISSUE TITLE
feat: `--progress` option

### ISSUE THREAD

**Issue by evilebottnawi** [webpack-contrib/webpack-command#7]
* Operating System: ubuntu 17.10
* Node Version: 10.0.0
* NPM Version: 6.0.0
* webpack Version: 4.6.0
* webpack-command Version: 0.1.

This issue is for a:

- [ ] **bug**
- [x] **feature** request
- [ ] **modification** request

##### CLI Command

```console
  $ webpack
```

##### webpack.config.js

no required

### Expected Behavior

Similar as `webpack-cli`

### Actual Behavior

```
✖ ｢webpack｣: Flags were specified that were not recognized:

  --progress  Not sure what you mean there
```

### How Do We Reproduce?

no required

### New Feature Use Case

Looks what is happens right now and build stage.

**Comment by evilebottnawi** [comment]
It is very helpful to DX when you have very many `import`'s, and webpack requires a lot of time on build. It seems that at the moment nothing is happening and webpack just hangs out.

**Comment by evilebottnawi** [comment]
Looks also `--profile` does not work because it is require Progress plugin https://github.com/webpack/webpack-cli/blob/8c9b8951ee0ce4a464cad74e0f6ee7407f891371/bin/webpack.js#L451

**Comment by shellscape** [comment]
@evilebottnawi thanks for the heads up 🍺  I'll have a look

(please do keep one issue for one problem in the future so we can organize them well)

**Comment by evilebottnawi** [comment]
@shellscape i know about one issue - one problem :smile: Just for you information :+1:

**Comment by ematipico** [comment]
Thanks for requesting this
