### ISSUE TITLE
Can't install webpack-command as global module

### ISSUE THREAD

**Issue by pravdomil** [webpack-contrib/webpack-command#8]
* Operating System: macos
* Node Version: latest
* NPM Version: latest
* webpack Version: latest
* webpack-command Version: latest

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### CLI Command

n/a

### Expected Behavior

Module is usable

### Actual Behavior

```console
webpack -h # Error: Cannot find module 'enhanced-resolve' 
```

### How Do We Reproduce?

```console
npm i webpack -g
npm i webpack-command -g
```

**Comment by shellscape** [comment]
Sad panda 🐼 😢  You removed the issue template, so we have to close your issue as invalid. Please don't ignore Issue or Pull Request templates.

**Comment by pravdomil** [comment]
it's obvious what the issue is, it fails run there is no reason for close

**Comment by shellscape** [comment]
@pravdomil we hold everyone to the same standard, even maintainers and collaborators. the warnings about the consequences of ignoring the issue template are also obvious. Please do not debate this.

**Comment by pravdomil** [comment]
reopen?

**Comment by shellscape** [comment]
Thank you for updating the issue.
